---

- name: Download telegraf package
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.13.2-1_amd64.deb
    dest: ~/telegraf_1.13.2-1_amd64.deb

- name: Installing package     
  apt:
    deb: ~/telegraf_1.13.2-1_amd64.deb

- name: Configuring filters
  shell: telegraf --input-filter cpu:mem:disk:diskio:kernel:system --output-filter influxdb config > /etc/telegraf/telegraf.conf   

- name: Configuring destination output
  shell: sed -i 's/# urls = \[\"http:\/\/127.0.0.1:8086\"\]/urls = \[\"http:\/\/innodb.bugoga.ga:8086\"\]/g' /etc/telegraf/telegraf.conf

- name: Install venv
  apt: name=virtualenv
  
  
- name: Move file
  copy:
    src: sh.sh
    dest: /tmp
    mode: '0755'

- name: Run shell
  shell: ./sh.sh
  args:
    chdir: /tmp    

- name: Move settings
  copy:
   src: settings.ini
   dest: /opt/srvstatus/
     
                  
- name: Insert plugin setup
  blockinfile:
   path: /etc/telegraf/telegraf.conf
   block: |
     [[inputs.exec]]
    
        commands = [
         "/opt/srvstatus/venv/bin/python /opt/srvstatus/service.py"
        ]
    
        timeout = "5s"
        name_override = "services_stats"
        data_format = "json"
        tag_keys = [
          "service"
        ]

- name: Telegraf start enable
  service: name=telegraf state=restarted enabled=yes
 