---
- hosts: tag_Environment_Staging
  gather_facts: true
  become: yes
  roles:     
     - mariadb-install
     - telegraf-install
     - tomcat9-install
     - galera-create
     - nginx-install-certificate
     
