---
- name: Upgrade System
  apt:
   update_cache: yes

- name: Install JAVA
  apt: name=default-jdk

- name: Install wget
  apt: name=wget

- name: Install unzip
  apt: name=unzip

- name: Add group "tomcat"
  group: name=tomcat

- name: Add user "tomcat"
  user: name=tomcat group=tomcat home=/opt/tomcat createhome=no
  become: True
  become_method: sudo

- name: Create tomcat directory
  file: name=/opt/tomcat state=directory

- name: Download Tomcat
  get_url:
    url: http://apache.ip-connect.vn.ua/tomcat/tomcat-9/v9.0.31/bin/apache-tomcat-9.0.31.tar.gz
    dest: /tmp

- name: Extract archive
  command: chdir=/opt/tomcat /bin/tar xvf /tmp/apache-tomcat-9.0.31.tar.gz -C /opt/tomcat/ creates=/opt/tomcat/apache-tomcat-9.0.31

- name: Symlink install directory
  file: src=/opt/tomcat/apache-tomcat-9.0.31 path=/opt/tomcat/latest state=link

- name: Change ownership of Tomcat installation
  file: path=/opt/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: COnfiguring daemon
  shell: sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'

- name: Daemon linking
  copy: src=tomcat.service dest=/etc/systemd/system/

- name: Set roles
  copy: src=tomcat-users.xml dest=/opt/tomcat/latest/conf/

- name: Tystemd daemon-reload
  shell: systemctl daemon-reload

- name: Tomcat9 start enable
  service: name=tomcat state=started enabled=yes
